name: CI/CD Pipeline for Docker Deployment

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the pipeline on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/wa-task-backend:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/wa-task-backend:latest .

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wa-task-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/wa-task-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker for Railway Deployment
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh

      # Authenticate to Railway using the RAILWAY_TOKEN
      - name: Authenticate with Railway
        run: |
          railway login --token ${{ secrets.RAILWAY_TOKEN }}

      # Deploy to Railway using Docker
      - name: Deploy to Railway
        run: |
          railway up --docker
